version: '3.8'
services:
  movies:
    image: narasimha4545/paymovies12:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  train:
    image: narasimha4545/paytrain12:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: narasimha4545/paytrain12:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: narasimha4545/payrecharge12
    ports:
      - "84:80"
    deploy:
      replicas: 3
